namespace ReactNativeStallionWindows
{
  [webhosthidden]
  [default_interface]
  runtimeclass ReactPackageProvider : Microsoft.ReactNative.IReactPackageProvider
  {
    ReactPackageProvider();
  };
  
  [webhosthidden]
  runtimeclass StallionWindows
  {
    static void ConfigureHost(
      Microsoft.ReactNative.ReactNativeHost host,
      Microsoft.ReactNative.ReactInstanceSettings settings,
      String defaultBundleRoot,
      String defaultBundleFile,
      String storageRoot);
    static void SetActive(Boolean active);
    static void Restart();
    static void Shutdown();
  };
}
