//
//  StallionVersion.h
//  react-native-stallion
//
//  Auto-generated from package.json during pod install
//  Do not edit this file manually
//

#ifndef StallionVersion_h
#define StallionVersion_h

#define STALLION_SDK_VERSION @"2.3.0"

#endif /* StallionVersion_h */
